### ISSUE TITLE
I got a filenotfound error

### ISSUE THREAD

**Issue by a18958** [linzhi2013/MitoZ#107]
Hi,
I ran the test file at all2 Module, it seems like can't create the ZZZ_mitoscaf.fa.gbf.
Here is the code:
`Traceback (most recent call last):
  File "/public/home/zhangxiuyue/tools/MitoZ/version_2.3/release_MitoZ_v2.3/bin/common/genbank_gene_stat_v2.py", line 238, in <module>
    main()
  File "/public/home/zhangxiuyue/tools/MitoZ/version_2.3/release_MitoZ_v2.3/bin/common/genbank_gene_stat_v2.py", line 202, in main
    seqid_len_topology_relatedSP = get_seq_topology_and_related_sp(gbfile=gbfile, closely_related_sp_file=closely_related_sp_file)
  File "/public/home/zhangxiuyue/tools/MitoZ/version_2.3/release_MitoZ_v2.3/bin/common/genbank_gene_stat_v2.py", line 173, in get_seq_topology_and_related_sp
    for rec in SeqIO.parse(gbfile, 'gb'):
  File "/public/home/zhangxiuyue/anaconda3/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/public/home/zhangxiuyue/anaconda3/lib/python3.6/site-packages/Bio/SeqIO/InsdcIO.py", line 93, in __init__
    super().__init__(source, mode="t", fmt="GenBank")
  File "/public/home/zhangxiuyue/anaconda3/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 47, in __init__
    self.stream = open(source, "r" + mode)

FileNotFoundError: [Errno 2] No such file or directory: 'test_mitoscaf.fa.gbf'
Error occured when running command:
/public/home/zhangxiuyue/anaconda3/bin/python3 /public/home/zhangxiuyue/tools/MitoZ/version_2.3/release_MitoZ_v2.3/bin/common/genbank_gene_stat_v2.py test_mitoscaf.fa.gbf test.most_related_species.txt all2 > summary.txt
`

**Comment by linzhi2013** [comment]
Sorry, I can't determine what's going on there, probably due to problems with installation. Maybe you could try Docker MitoZ-v2.3, or Udocker version which doesn't need sudo privileges.

**Comment by a18958** [comment]
Sorry for my late reply,
it works well in the Docker, thank you!
Cheers!

**Comment by linzhi2013** [comment]
That's great!
