### ISSUE TITLE
Annotation of Fasta sequences. Error.

### ISSUE THREAD

**Issue by dskostin** [linzhi2013/MitoZ#121]
Hi all,
I'm trying to annotate assembled by using NOVOplasty mitochondrial genomes of four congeneric species. After finishing annotation process (as far as I understand, draft annotation), MitoZ download taxdump.tar.gz from NCBI FTP site, and get errors (differ errors for different sequenses).
...
convert result to gff3 format
Annotation finished

And then I get three types of errors (pasted bellow). What could be the reason of it? I would be grateful for any clue.

....
NCBI database not present yet (first time used?)
Downloading taxdump.tar.gz from NCBI FTP site...
Done. Parsing...
Loading node names...
Traceback (most recent call last):
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 183, in <module>
    main()
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 169, in main
    cds_taxa_file = get_lineage_for_cds(cdspos=cds_pos_file)
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 140, in get_lineage_for_cds
    rank_dict = get_rank_dict(taxa_name=species)
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 58, in get_rank_dict
    ncbi = NCBITaxa()
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 86, in __init__
    self.update_taxonomy_database()
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 113, in update_taxonomy_database
    update_db(self.dbfile)
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 725, in update_db
    t, synonyms = load_ncbi_tree_from_dump(tar)
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 649, in load_ncbi_tree_from_dump
    for line in tar.extractfile("names.dmp"):
  File "/app/anaconda/lib/python3.6/tarfile.py", line 2069, in extractfile
    tarinfo = self.getmember(member)
  File "/app/anaconda/lib/python3.6/tarfile.py", line 1743, in getmember
    tarinfo = self._getmember(name)
  File "/app/anaconda/lib/python3.6/tarfile.py", line 2325, in _getmember
    members = self.getmembers()
  File "/app/anaconda/lib/python3.6/tarfile.py", line 1754, in getmembers
    self._load()        # all members, we first have to
  File "/app/anaconda/lib/python3.6/tarfile.py", line 2348, in _load
    tarinfo = self.next()
  File "/app/anaconda/lib/python3.6/tarfile.py", line 2279, in next
    self.fileobj.seek(self.offset - 1)
  File "/app/anaconda/lib/python3.6/gzip.py", line 368, in seek
    return self._buffer.seek(offset, whence)
  File "/app/anaconda/lib/python3.6/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/app/anaconda/lib/python3.6/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid distance code
Error occured when running command:
/app/anaconda/bin/python3 /app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py simensis_mitoscaf.fa.solar.genewise.gff.cds.position.cds simensis_mitoscaf.fa simensis.most_related_species.txt 

## or:
NCBI database not present yet (first time used?)
Downloading taxdump.tar.gz from NCBI FTP site...
Traceback (most recent call last):
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 183, in <module>
    main()
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 169, in main
    cds_taxa_file = get_lineage_for_cds(cdspos=cds_pos_file)
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 140, in get_lineage_for_cds
    rank_dict = get_rank_dict(taxa_name=species)
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 58, in get_rank_dict
    ncbi = NCBITaxa()
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 86, in __init__
    self.update_taxonomy_database()
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 113, in update_taxonomy_database
    update_db(self.dbfile)
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 720, in update_db
    urlretrieve("ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz", "taxdump.tar.gz")
  File "/app/anaconda/lib/python3.6/urllib/request.py", line 289, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 26347808 out of 55146922 bytes>
Error occured when running command:
/app/anaconda/bin/python3 /app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py chrysopus_mitoscaf.fa.solar.genewise.gff.cds.position.cds chrysopus_mitoscaf.fa chrysopus.most_related_species.txt 

# or:

Downloading taxdump.tar.gz from NCBI FTP site...
Done. Parsing...
Loading node names...
Traceback (most recent call last):
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 183, in <module>
    main()
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 169, in main
    cds_taxa_file = get_lineage_for_cds(cdspos=cds_pos_file)
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 140, in get_lineage_for_cds
    rank_dict = get_rank_dict(taxa_name=species)
  File "/app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py", line 58, in get_rank_dict
    ncbi = NCBITaxa()
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 86, in __init__
    self.update_taxonomy_database()
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 113, in update_taxonomy_database
    update_db(self.dbfile)
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 725, in update_db
    t, synonyms = load_ncbi_tree_from_dump(tar)
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 649, in load_ncbi_tree_from_dump
    for line in tar.extractfile("names.dmp"):
  File "/app/anaconda/lib/python3.6/tarfile.py", line 2069, in extractfile
    tarinfo = self.getmember(member)
  File "/app/anaconda/lib/python3.6/tarfile.py", line 1743, in getmember
    tarinfo = self._getmember(name)
  File "/app/anaconda/lib/python3.6/tarfile.py", line 2325, in _getmember
    members = self.getmembers()
  File "/app/anaconda/lib/python3.6/tarfile.py", line 1754, in getmembers
    self._load()        # all members, we first have to
  File "/app/anaconda/lib/python3.6/tarfile.py", line 2348, in _load
    tarinfo = self.next()
  File "/app/anaconda/lib/python3.6/tarfile.py", line 2279, in next
    self.fileobj.seek(self.offset - 1)
  File "/app/anaconda/lib/python3.6/gzip.py", line 368, in seek
    return self._buffer.seek(offset, whence)
  File "/app/anaconda/lib/python3.6/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/app/anaconda/lib/python3.6/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
Error occured when running command:
/app/anaconda/bin/python3 /app/release_MitoZ_v2.3/bin/annotate/pick_most_related_sp_from_position_cds.py chrysopus_mitoscaf.fa.solar.genewise.gff.cds.position.cds chrysopus_mitoscaf.fa chrysopus.most_related_species.txt

**Comment by linzhi2013** [comment]
Hi dskostin,

It's unnormal for MitoZ to try to download the NCBI taxonomy database every time.

Would you tell me how did you install MitoZ? From source code? or from MitoZ Singularity v2.3? If that's the case, please enter your `mitozEnv` or Singularity container, and check if the taxonomy database exists or not:

In the terminal, type `python3`, then you will enter the Python3 command-line status.

execute following commands in Python3
```
>from ete3 import NCBITaxa
 >ncbi = NCBITaxa()
 >ncbi.update_taxonomy_database()

```
 
If something wrong in this step, which just indicates that your NCBI taxonomy database is not well installed, which could be due to there is not enough space left in your HOME directory.

**Comment by dskostin** [comment]
Hi @linzhi2013 ,
Thanks a lot for your answer. I have spend several days trying to fix it, but it still does not work. Let we to add some additional info, I still want to force this script work correctly.

I installed MitoZ by using Singularity. When I launch python3 from comand line into the Singularity folder, I get an error "ModuleNotFoundError: No module named 'ete3'"

I checked available space in my home directory - 98 Gb. It should be enough, I guess.
Could you please advice me something? Maybe shall I try to re-install MitoZ, by using another way, for instance, from source code?

**Comment by linzhi2013** [comment]
Dear dskostin,

I just found out that Singularity has rebuilt all my images on April 25, 2021. Maybe there is something wrong with the newly built images.

You can try to get a MitoZ container from https://pan.genomics.cn/ucdisk/s/uMFvum firstly.

Please make sure you are using the Python 3 inside the Singularity container.

I'm trying to download the newly built image and to verify my guess.

Cheers

**Comment by linzhi2013** [comment]
Just to FYI, I found the newly built image (Singularity MitoZ v2.3) also works for me.

**Comment by dskostin** [comment]
Just to inform. I solved my issue, the problem was solved by re-installation of ete3 package.
Now MitoZ is working, 
Great thanks!

**Comment by linzhi2013** [comment]
That's great!
