### ISSUE TITLE
A annotation error when running all module

### ISSUE THREAD

**Issue by user1-10** [linzhi2013/MitoZ#127]
Hi, dear Meng, I meet a problem of annotation when running all module. After the annotation finished, it showed no result. Is the problem of ete3?
the erron was attached in the following:
2021-07-07 01:08:35
export WISECONFIGDIR=/lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/wisecfg
perl /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -i work71.hmmtblout.besthit.sim.fa -d /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Animal_CDS_protein.fa -cpu 12 -g 5 -o ./

**Sorry, the annotation finished with no result**!

makeblastdb -in work71.hmmtblout.besthit.sim.fa -dbtype nucl
run the tblastn shell file
Run solar to conjoin HSPs and filter bad HSPs and redundance.
preparing genewise input directories and files
name gi_NC_009093_ATP6_Galendromus_occidentalis_222_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 3091.
name gi_NC_009093_ATP8_Galendromus_occidentalis_53_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 6665.
name gi_NC_009093_COX1_Galendromus_occidentalis_517_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 9629.
name gi_NC_009093_COX2_Galendromus_occidentalis_221_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 12383.
name gi_NC_009093_COX3_Galendromus_occidentalis_275_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 15953.
name gi_NC_009093_CYTB_Galendromus_occidentalis_357_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 19517.
name gi_NC_009093_ND1_Galendromus_occidentalis_270_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 23099.
name gi_NC_009093_ND4_Galendromus_occidentalis_437_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 33775.
name gi_NC_009093_ND4L_Galendromus_occidentalis_89_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 37351.
name gi_NC_009093_ND5_Galendromus_occidentalis_560_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 40913.
name gi_NC_KM273123_COX3_Drepane_punctata_261_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 83213.
name gi_NC_KP164983_COX3_Drepane_longimana_261_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 87659.
name gi_NC_010292_CYTB_Heteronotia_binoei_379_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 98393.
name gi_NC_019615_ND5_Hoplobatrachus_rugulosus_611_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 144729.
name gi_NC_027267_ND6_Phalacrocorax_carbo_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 152161.
name gi_NC_018340_ND6_Champsocephalus_gunnari_174_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 153949.
name gi_NC_025925_ND6_Ixobrychus_sinensis_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 154499.
name gi_NC_025924_ND6_Ixobrychus_eurhythmus_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 154503.
name gi_NC_025923_ND6_Botaurus_stellaris_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 154507.
name gi_NC_025922_ND6_Butorides_striata_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 154511.
name gi_NC_025921_ND6_Ardeola_bacchus_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 154515.
name gi_NC_025920_ND6_Egretta_sacra_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 154519.
name gi_NC_015087_ND6_Penelopides_panini_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 155151.
name gi_NC_015085_ND6_Aceros_waldeni_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 155155.
name gi_NC_029147_ND6_Turdus_philomelos_171_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 156555.
name gi_NC_029140_ND6_Notiomystis_cincta_172_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 156569.
name gi_NC_026190_ND6_Phoebastria_albatrus_175_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 157075.
name gi_NC_026189_ND6_Phoebastria_immutabilis_175_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 157079.
name gi_NC_026188_ND6_Phoebastria_nigripes_175_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 157083.
name gi_NC_010292_ND6_Heteronotia_binoei_173_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 159083.
name gi_NC_007172.2_ND6_Thalassarche_melanophrys_175_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 159239.
name gi_NC_016465_COX1_Clava_multicornis_521_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 160481.
name gi_NC_026908_ATP6_Illex_argentinus_230_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 164365.
name gi_NC_020348_ATP6_Ommastrephes_bartramii_230_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 164435.
name gi_NC_016423_ATP6_Bathyteuthis_abyssicola_230_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 164513.
name gi_NC_007893_ATP6_Watasenia_scintillans_230_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 164857.
name gi_NC_006354_ATP6_Todarodes_pacificus_230_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 164865.
name gi_NC_011581_ATP6_Architeuthis_dux_230_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 164873.
name gi_NC_010636_ATP6_Sthenoteuthis_oualaniensis_230_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 164877.
name gi_NC_009734_ATP6_Dosidicus_gigas_230_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 164887.
name gi_NC_026908_ATP8_Illex_argentinus_51_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165019.
name gi_NC_020348_ATP8_Ommastrephes_bartramii_51_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165087.
name gi_NC_016423_ATP8_Bathyteuthis_abyssicola_51_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165143.
name gi_NC_007893_ATP8_Watasenia_scintillans_51_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165421.
name gi_NC_006354_ATP8_Todarodes_pacificus_51_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165429.
name gi_NC_011581_ATP8_Architeuthis_dux_51_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165437.
name gi_NC_010636_ATP8_Sthenoteuthis_oualaniensis_51_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165441.
name gi_NC_009734_ATP8_Dosidicus_gigas_51_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165451.
name gi_NC_026908_COX1_Illex_argentinus_510_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165593.
name gi_NC_020348_COX1_Ommastrephes_bartramii_510_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165669.
name gi_NC_016423_COX1_Bathyteuthis_abyssicola_510_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 165749.
name gi_NC_007893_COX1_Watasenia_scintillans_510_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166083.
name gi_NC_011581_COX1_Architeuthis_dux_510_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166097.
name gi_NC_010636_COX1_Sthenoteuthis_oualaniensis_510_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166101.
name gi_NC_009734_COX1_Dosidicus_gigas_510_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166111.
name gi_NC_020348_COX2_Ommastrephes_bartramii_229_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166331.
name gi_NC_016423_COX2_Bathyteuthis_abyssicola_228_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166405.
name gi_NC_007893_COX2_Watasenia_scintillans_228_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166743.
name gi_NC_011581_COX2_Architeuthis_dux_228_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166757.
name gi_NC_010636_COX2_Sthenoteuthis_oualaniensis_229_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166761.
name gi_NC_009734_COX2_Dosidicus_gigas_229_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166771.
name gi_NC_026908_COX3_Illex_argentinus_259_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166923.
name gi_NC_020348_COX3_Ommastrephes_bartramii_259_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 166999.
name gi_NC_007893_COX3_Watasenia_scintillans_259_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 167411.
name gi_NC_006354_COX3_Todarodes_pacificus_259_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 167417.
name gi_NC_011581_COX3_Architeuthis_dux_259_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 167425.
name gi_NC_010636_COX3_Sthenoteuthis_oualaniensis_259_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 167429.
name gi_NC_009734_COX3_Dosidicus_gigas_259_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 167439.
name gi_NC_008828_ATP6_Hexamermis_agrotis_175_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 173019.
name gi_NC_008828_ATP6_Hexamermis_agrotis_175_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 173021.
name gi_NC_008693_ND3_Romanomermis_iyengari_115_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 175141.
name gi_NC_008640_ND3_Romanomermis_culicivorax_117_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 175147.
name gi_NC_008640_ND3_Romanomermis_culicivorax_117_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 175149.
name C219843 is not uniq at /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 55.
run the genewise shell file
running genewise
convert result to gff3 format
**cat: ./work71.hmmtblout.besthit.sim.fa.genewise/*/*.genewise: No such file or directory**
Traceback (most recent call last):
  File "/lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py", line 335, in <module>
    filter_taxa(annt_fa=args.fa, cdspos=cdsposcds_file, outf=args.outf,
  File "/lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py", line 198, in filter_taxa
    with open(cdspos, 'r') as fh, open(cdspos_taxa_log, 'w') as fh_taxalog:
FileNotFoundError: [Errno 2] No such file or directory: 'work71.hmmtblout.besthit.sim.fa.solar.genewise.gff.cds.position.cds'
Error occured when running command:
/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/bin/python3 /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py -fa work71.hmmtblout.besthit.sim.fa -MTsoft /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -db /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Animal_CDS_protein.fa -thread 12 -genetic_code 5 -requiring_taxa 'Arthropoda' -relax 0 -WISECONFIGDIR /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/wisecfg -outf work71.hmmtblout.besthit.sim.filtered.fa

**Comment by user1-10** [comment]
Dear Meng,
    The last problem has been resolved, and I follow the install instruction to rebuild a new environment. But, a new problem has been occured when running the annotation. I think the NCBI data is fine. The error showed something was bug in the program.
**The error has been attached in the following:**
convert result to gff3 format
Traceback (most recent call last):
  **File "/lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/prepare_CDSposition.py", line 47, in <module>
    fh_in = open(in_f, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/HS38_mitoscaf.fa.solar.genewise.gff.cds.position.cds'**
Error occured when running command:
/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/bin/python3 /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/bin/annotate/prepare_CDSposition.py /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/HS38_mitoscaf.fa.solar.genewise.gff.cds.position.cds /lustre/home/acct-ioozds/ioozds/yc/release_MitoZ_v2.4-alpha/HS38.cds.position

I would appreciate if you can tell me how to edit the program of prepare_CDSposition.py.

Thanks
best wishes,
user1-10

**Comment by hanqi-p** [comment]
Hello, have you solved this problem? I made the same mistake.

**Comment by user1-10** [comment]
Yes, I have solved it. 
The problem happened in the process of installment.
If you use the source code to install, the main problem was occured in the 4.3.2 (Set up an isolated enviroment for MitoZ).
You should not just copy the  command of the guide. It would be better to install each package one by one to confirm all the packages had been installed.
So, remove it and re-install Mitoz.

**Comment by linzhi2013** [comment]
Hope the new version (MitoZ 3.0) can solve the problem via the Conda package manager.
