### ISSUE TITLE
NCBI taxa database issue

### ISSUE THREAD

**Issue by dinhe878** [linzhi2013/MitoZ#129]
Hi,

I am trying to run MitoZ on our HPC, and the app is available though the environment module system.

I've tried many different methods found here in the issue forum but still kept getting the same problem. Here I tried the singularity image (shub://linzhi2013/MitoZ:v2.3) and built a sandbox (so I don't need to reinitiate the img every time) in my directory.

Also, I'm aware of the /home disk space issue, so I've created a folder where no disk space limit is in place and linked to my /home 

Then I navigate to my custom etetoolkit/ folder, execute python3 from the sandbox directory and do:

```
from ete3 import NCBITaxa
ncbi = NCBITaxa()
ncbi.update_taxonomy_database()

``` 
And I got the error messages:

> Uploading to /home/people/dinghe/.etetoolkit/taxa.sqlite
> 
> Inserting synonyms:      175000 Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/projects/ku_00039/people/dinghe/working_dr/mito_genome_assembly/MitoZ_03082021/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 86, in __init__
>     self.update_taxonomy_database()
>   File "/home/projects/ku_00039/people/dinghe/working_dr/mito_genome_assembly/MitoZ_03082021/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 113, in update_taxonomy_database
>     update_db(self.dbfile)
>   File "/home/projects/ku_00039/people/dinghe/working_dr/mito_genome_assembly/MitoZ_03082021/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 740, in update_db
>     upload_data(dbfile)
>   File "/home/projects/ku_00039/people/dinghe/working_dr/mito_genome_assembly/MitoZ_03082021/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 779, in upload_data
>     db.execute("INSERT INTO synonym (taxid, spname) VALUES (?, ?);", (taxid, spname))
> sqlite3.IntegrityError: UNIQUE constraint failed: synonym.spname, synonym.taxid
> 

Any idea how to solve this? 

Many thanks!

**Comment by dinhe878** [comment]
I updated the database using a separate ete3 conda environment, solved this issue. However, I ran into another problem which I will open a new issue. Now I close this one.
