### ISSUE TITLE
I got an error when I install the taxdump.tar.gz into sqlite3, why ?

### ISSUE THREAD

**Issue by taotaoyuan** [linzhi2013/MitoZ#169]
>>> from ete3 import NCBITaxa
>>> NCBITaxa(taxdump_file='/home/lx_sky6/yt/soft/MitoZ-master/version_2.4-alpha/taxdump.tar.gz')
Loading node names...
2464628 names loaded.
286300 synonyms loaded.
Loading nodes...
2464628 nodes loaded.
Linking nodes...
Tree is loaded.
Updating database: /home/lx_sky6/.etetoolkit/taxa.sqlite ...
 2464000 generating entries... 
Uploading to /home/lx_sky6/.etetoolkit/taxa.sqlite

Inserting synonyms:      35000 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lx_sky6/software/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 106, in __init__
    self.update_taxonomy_database(taxdump_file)
  File "/home/lx_sky6/software/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 131, in update_taxonomy_database
    update_db(self.dbfile, taxdump_file)
  File "/home/lx_sky6/software/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 760, in update_db
    upload_data(dbfile)
  File "/home/lx_sky6/software/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 802, in upload_data
    db.execute("INSERT INTO synonym (taxid, spname) VALUES (?, ?);", (taxid, spname))
sqlite3.IntegrityError: UNIQUE constraint failed: synonym.spname, synonym.taxid

**Comment by linzhi2013** [comment]
Hi,

You can check for similar issues at https://github.com/linzhi2013/MitoZ/issues?q=UNIQUE+constraint+failed+ 

Cheers

**Comment by linzhi2013** [comment]
One reason could be due to a lower version of ete3.

You can try the conda-pack or Docker/Singuarity versions of MitoZ.

Best
