### ISSUE TITLE
Error in genbank_gene_stat_v2.py

### ISSUE THREAD

**Issue by kabilov** [linzhi2013/MitoZ#17]
Hi Guanliang!

I installed MitoZ by docker (v2.3 and 2.4a) and tried to analyze mitogenome but I see always the same error.

Variants of command line:
1)  python3 /app/release_MitoZ_v2.4-alpha/MitoZ.py all --genetic_code 1 --clade Chordata --thread_number 13 --outprefix duck-01 --fastq1 duck-01_S10_L001_R1_001.fastq.gz --fastq2 duck-01_S10_L001_R2_001.fastq.gz --fastq_read_length 300 --insert_size 300 --run_mode 2 --filter_taxa_method 1 --requiring_taxa 'Chordata'

2)   python3 /app/release_MitoZ_v2.4-alpha/MitoZ.py annotate --fastafile duck.fa --genetic_code 1 --clade Chordata --thread_number 13 --outprefix duck.fa

3)  python3 /app/release_MitoZ_v2.3/MitoZ.py annotate --fastafile duck.fa --genetic_code 1 --clade Chordata --thread_number 13 --outprefix duck.fa

In all cases it was error such type:
/app/anaconda/bin/python3 /app/release_MitoZ_v2.4-alpha/bin/common/genbank_gene_stat_v2.py duck-01_mitoscaf.fa.gbf duck-01.most_related_species.txt all > summary.txt

Traceback (most recent call last):
  File "/app/release_MitoZ_v2.4-alpha/bin/common/genbank_gene_stat_v2.py", line 238, in <module>
    main()
  File "/app/release_MitoZ_v2.4-alpha/bin/common/genbank_gene_stat_v2.py", line 215, in main
    gene_infor, gene_freq = gene_stat(gbfile)
  File "/app/release_MitoZ_v2.4-alpha/bin/common/genbank_gene_stat_v2.py", line 97, in gene_stat
    print(ass_num, "Warning: NO gene or product tag! this gene is not output!\n")
NameError: name 'ass_num' is not defined
Error occured when running command:
/app/anaconda/bin/python3 /app/release_MitoZ_v2.4-alpha/bin/common/genbank_gene_stat_v2.py duck-01_mitoscaf.fa.gbf duck-01.most_related_species.txt all > summary.txt

Could you help with this bug?

Best wishes,
Marsel

**Comment by linzhi2013** [comment]
Hi Marsel,

What species do you have? The genetic code of mitochondrial genome for Chordata should be ``2``,  not ``1``.

Did you already obtain the mitogenome sequence? If yes, you may just ``annotate`` the sequence and see if it was the problem with the ``--genetic_code 1``? ``annotate`` is quite fast.

Cheers,
Guanliang

**Comment by linzhi2013** [comment]
I'm closing this. You can reopen it if the problem is still there.
