### ISSUE TITLE
All sequences are low abundance (<10X) -- RNA Seq data

### ISSUE THREAD

**Issue by linzhi2013** [linzhi2013/MitoZ#179]
Starting with this code:

mitoz all \
--outprefix mg \
--thread_number 20 \
--clade Arthropoda \
--genetic_code 5 \
--species_name "-----------" \               # name false
--fq1 /guest/triatominae/tiagob/mitogenome/mg_R1.fastq.gz \
--fq2 /guest/triatominae/tiagob/mitogenome/mg_R2.fastq.gz \
--fastq_read_length 151 \
--data_size_for_mt_assembly 0.3 \
--assembler megahit \
--kmers_megahit 59 79 99 119 141 \
--memory 50 \
--requiring_taxa Arthopoda 

I have this error:

filter_by_abundance():
All sequences are low abundance (<10X)
Traceback (most recent call last):
  File "/guest/triatominae/tiagob/mitogenome/mitoz3.4/bin/mitoz", line 8, in <module>
    sys.exit(main())
  File "/guest/triatominae/tiagob/mitogenome/mitoz3.4/lib/python3.8/site-packages/mitoz/MitoZ.py", line 88, in main
    args.func(args)
  File "/guest/triatominae/tiagob/mitogenome/mitoz3.4/lib/python3.8/site-packages/mitoz/all/all.py", line 289, in main
    args.fastafiles, assemble_all_result_wdir = mitoz.assemble.main(assemble_args)
  File "/guest/triatominae/tiagob/mitogenome/mitoz3.4/lib/python3.8/site-packages/mitoz/assemble/assembly.py", line 480, in main
    assembly_file, mt_file = use_megahit(
  File "/guest/triatominae/tiagob/mitogenome/mitoz3.4/lib/python3.8/site-packages/mitoz/assemble/assembly.py", line 388, in use_megahit
    mt_file = findmitoscaf.main(args)
  File "/guest/triatominae/tiagob/mitogenome/mitoz3.4/lib/python3.8/site-packages/mitoz/findmitoscaf/findmitoscaf.py", line 444, in main
    selected_mt_fa = select_sequences_by_gene_completeness(
  File "/guest/triatominae/tiagob/mitogenome/mitoz3.4/lib/python3.8/site-packages/mitoz/findmitoscaf/findmitoscaf.py", line 248, in select_sequences_by_gene_completeness
    hmm_outf_tbl_besthit_sim_fasta_like + ".sorted"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

The error happens even using few reads.

_Originally posted by @TiagoBelintani in https://github.com/linzhi2013/MitoZ/discussions/178_

**Comment by linzhi2013** [comment]
Check the file `DM01.megahit.hmmtblout.besthit.sim.filtered-by-taxa.low_abundance.fasta` (https://github.com/linzhi2013/MitoZ/wiki/Tutorial#2-the-mitogenome-assembly-step) .

If All sequences are low abundance (<10X), MitoZ will exit, because we consider the low abundance sequences are not reliable.

**Comment by linzhi2013** [comment]
[TiagoBelintani](https://github.com/TiagoBelintani)
[2 hours ago](https://github.com/linzhi2013/MitoZ/discussions/178#discussioncomment-4736720)
Author
Thanks.

I switched to Spades and updated the assembler packages and dependencies.

Also, I added the parameter kmers_spades as "auto".

It's still running, but no issues.

Yours sincerely.

**Comment by linzhi2013** [comment]
> If All sequences are low abundance (<10X),

there is a `--min_abundance` option to set the cutoff.
