### ISSUE TITLE
Test data run: "TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' "

### ISSUE THREAD

**Issue by awsdd** [linzhi2013/MitoZ#186]
Hello,

I've installed v3.5 with Conda as per the instructions and am attempting to run the test data files. Command is as follows (same as on the installation page):

```
mitoz all --fq1 test.1.fq.gz  --fq2 test.2.fq.gz --outprefix ttt --clade Arthropoda --data_size_for_mt_assembly 0 --assembler megahit --requiring_taxa Arthropoda
```

but I'm getting the following error
```
[bwa_idx_build] fail to open file 'ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa.fa' : No such file or directory
Error occured when running command:
bwa index ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa.fa

2023-04-01 20:14:50,299 - mitoz.utility.utility - ERROR - 
Error occured when running command:
/home/chaph97p/.conda/envs/mitozEnv/bin/python3.6 /home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/findmitoscaf/script/cal_bwa_abundance.py -fa ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa.fa -fq1 /scratch/phoebe/mitogenomes/mitoz/clean_data/ttt.clean_R1.fq.gz -fq2 '/scratch/phoebe/mitogenomes/mitoz/clean_data/ttt.clean_R2.fq.gz'  -out ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa.fa.abun.fa -bwa bwa  -samtools samtools -thread 8


2023-04-01 20:14:50,300 - mitoz.utility.utility - INFO - 
/home/chaph97p/.conda/envs/mitozEnv/bin/python3.6 /home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/findmitoscaf/script/filter_by_abundance.py 'abun\=([0-9]+\.*[0-9]*)'  10  ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa  ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa.fa.abun.fa 
Traceback (most recent call last):
  File "/home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/findmitoscaf/script/filter_by_abundance.py", line 60, in <module>
    main()
  File "/home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/findmitoscaf/script/filter_by_abundance.py", line 55, in main
    min_abundance=float(min_abundance)
  File "/home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/findmitoscaf/script/filter_by_abundance.py", line 16, in filter_by_abundance
    with open(in_sim, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa'

2023-04-01 20:14:50,752 - mitoz.utility.utility - ERROR - 
Error occured when running command:
/home/chaph97p/.conda/envs/mitozEnv/bin/python3.6 /home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/findmitoscaf/script/filter_by_abundance.py 'abun\=([0-9]+\.*[0-9]*)'  10  ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa  ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa.fa.abun.fa 


2023-04-01 20:14:50,753 - mitoz.utility.utility - INFO - 
cp -r ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa.low_abundance /scratch/phoebe/mitogenomes/mitoz/mt_assembly/ttt.megahit.result

2023-04-01 20:14:50,775 - mitoz.utility.utility - WARNING - 
filter_by_abundance():
All sequences are low abundance (<10X)
Traceback (most recent call last):
  File "/home/chaph97p/.conda/envs/mitozEnv/bin/mitoz", line 10, in <module>
    sys.exit(main())
  File "/home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/MitoZ.py", line 99, in main
    args.func(args)
  File "/home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/all/all.py", line 332, in main
    args.fastafiles, assemble_all_result_wdir = mitoz.assemble.main(assemble_args)
  File "/home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/assemble/assembly.py", line 501, in main
    logger=logger)
  File "/home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/assemble/assembly.py", line 397, in use_megahit
    mt_file = findmitoscaf.main(args)
  File "/home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/findmitoscaf/findmitoscaf.py", line 455, in main
    logger=logger)
  File "/home/chaph97p/.conda/envs/mitozEnv/lib/python3.6/site-packages/mitoz/findmitoscaf/findmitoscaf.py", line 253, in select_sequences_by_gene_completeness
    hmm_outf_tbl_besthit_sim_fasta_like + ".sorted"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
Same thing happens when changing the assembler to spades and I've tried deleting the and reinstalling the environment/Mitoz, and redownloading the test files (they are in the current working directory when I run the command). 

ttt.megahit.hmmtblout.besthit.sim.filtered-by-taxa.low_abundance is empty.

Any ideas what might be going on here? Thanks for any assistance.

**Comment by linzhi2013** [comment]
Hi [awsdd](https://github.com/awsdd),

on which platform (Mac OS, Linux?) are you running MitoZ?

It looks like some installation problems.

**Comment by linzhi2013** [comment]
When using Singularity, please make sure `--fq1 8004-02-32-1_S1_L001_R1_001.fastq.gz --fq2 8004-02-32-1_S1_L001_R2_001.fastq.gz` are the real files, NOT soft-links. 

Soft links pointing to other directories can NOT be read by Docker or Singularity if you do not explicitly mount these directories to the container (`--bind ` or `-v ` option).

**Comment by awsdd** [comment]
Thanks. I checked that the files weren't soft links, which they weren't - but I did (embarrassingly) notice an error in the file names in the command, which would explain why mitoz couldn't find the path. However, with this corrected I still got the same error (just with the file paths filled in where they previously became empty).

I deleted the results from the test files, which were still in the same directory, and it seems that has solved the issue - my files have just successfully run.

**Comment by linzhi2013** [comment]
> I deleted the results from the test files, which were still in the same directory, and it seems that has solved the issue - my files have just successfully run.

Great, you can try the run in a new directory to avoid potential issues caused by previous runs.

**Comment by linzhi2013** [comment]
Please upgrade to MitoZ 3.6 due to a bug in MitoZ 3.5 (tRNA gene annotation failed)
