### ISSUE TITLE
About --assembler spades

### ISSUE THREAD

**Issue by xjt1234** [linzhi2013/MitoZ#193]
## Conda 
Hello developer, I encountered a problem when assembling mitochondrial genome with spades. First of all, the command skip filter cannot be used when assembling software with spades, which means that quality control cannot be skipped. 2. I use this code to assemble 
```
mitoz all \
--outprefix mito_2_XDND \
--thread_number 40 \
--fq1 /home/data/t200301/hll/reassemble/XDND/Insect_Y298-01-R91_good_2.fq.gz \
--fq2  /home/data/t200301/hll/reassemble/XDND/Insect_Y298-01-R91_good_1.fq.gz \
--requiring_taxa "Arthropoda" \
--skip_filter  \
--assembler spades \
--memory 200 
```
was double-ended sequencing data but the following Error was reported 

```
== Error == system call for: "['/home/data/t200301/miniconda3/envs/mitozEnv/bin/spades-hammer',  '/home/data/t200301/hll/reassemble/XDND/mt_assembly/metaspades/corrected/configs/config.info']" finished abnormally,  OS return value: 255

None



In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru

or report an issue on our GitHub repository github.com/ablab/spades

Please provide us with params.txt and spades.log files from the output directory.



SPAdes log can be found here: /home/data/t200301/hll/reassemble/XDND/mt_assembly/metaspades/spades.log



Thank you for using SPAdes!



2023-05-18 09:08:52, 741-mitoz.utility.utility - ERROR -

Error occured when running command:

spades.py  --checkpoints all  -o /home/data/t200301/hll/reassemble/XDND/mt_assembly/metaspades --meta  --pe1-1  /home/data/t200301/hll/reassemble/XDND/clean_data/mito_2_XDND.clean_R1.fq.gz --pe1-2  /home/data/t200301/hll/reassemble/XDND/clean_data/mito_2_XDND.clean_R2.fq.gz --threads 40 -k auto --memory 200





2023-05-18 09:08:52, 742-mitoz.utility. utility - WARNING -

Can not find assembly_file: /home/data/t200301/hll/reassemble/XDND/mt_assembly/metaspades/scaffolds.fasta

Traceback (most recent call last):

File "/home/data/t200301/miniconda3/envs/mitozEnv/bin/mitoz", line 10, in &lt; module&gt;

sys.exit(main())

File "/ home/data/t200301 / miniconda3 / envs mitozEnv/lib/python3.8 / site - packages/mitoz/mitoz. Py", line 99, in the main

args.func(args)

The File "/ home/data/t200301 / miniconda3 / envs/mitozEnv/lib/python3.8 / site - packages/mitoz/all/all py", line 361, in the main

args.fastafiles, assemble_all_result_wdir = mitoz.assemble.main(assemble_args)

File "/ home/data/t200301 miniconda3 envs/mitozEnv/lib/python3.8 / site - packages/mitoz/assemble/assembly. Py", line 521, in main

logger.info('assemble.main() found resulting_mt_files:\n' + '\n'.join(resulting_mt_files))

TypeError: sequence item 0: expected str instance, NoneType found 
```

**Comment by xjt1234** [comment]
Hi, developer, i used the code that you gave to me. But it still reports this error:\

== Error ==  system call for: "['/home/data/t200301/miniconda3/envs/mitozEnv/bin/spades-hammer', '/home/data/t200301/hll/reassemble/XDND/mt_assembly/metaspades/corrected/configs/config.info']" finished abnormally, OS return value: 255
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/data/t200301/hll/reassemble/XDND/mt_assembly/metaspades/spades.log

Thank you for using SPAdes!

**Comment by linzhi2013** [comment]
If you read the links, you can get the answers...

I also added the solution to https://github.com/linzhi2013/MitoZ/wiki/New-Features#2-two-new-assemblers .

**Comment by xjt1234** [comment]
Thank you, thank you very much. I've seen it before, but I can't find it anymore. I'm so sorry
