### ISSUE TITLE
在select_sequences_by_gene_completeness函数中，运行时出现了错误

### ISSUE THREAD

**Issue by liyu123321** [linzhi2013/MitoZ#203]
All sequences are low abundance (<10X)
Traceback (most recent call last):
File "/home/dell/soft/mitoz3.6/bin/mitoz", line 10, in <module>
sys.exit(main())
File "/home/dell/soft/mitoz3.6/lib/python3.8/site-packages/mitoz/MitoZ.py", line 99, in main
args.func(args)
File "/home/dell/soft/mitoz3.6/lib/python3.8/site-packages/mitoz/all/all.py", line 361, in main
args.fastafiles, assemble_all_result_wdir = mitoz.assemble.main(assemble_args)
File "/home/dell/soft/mitoz3.6/lib/python3.8/site-packages/mitoz/assemble/assembly.py", line 507, in main
assembly_file, mt_file = use_megahit(
File "/home/dell/soft/mitoz3.6/lib/python3.8/site-packages/mitoz/assemble/assembly.py", line 405, in use_megahit
mt_file = findmitoscaf.main(args)
File "/home/dell/soft/mitoz3.6/lib/python3.8/site-packages/mitoz/findmitoscaf/findmitoscaf.py", line 556, in main
selected_mt_fa = select_sequences_by_gene_completeness(
File "/home/dell/soft/mitoz3.6/lib/python3.8/site-packages/mitoz/findmitoscaf/findmitoscaf.py", line 299, in select_sequences_by_gene_completeness
hmm_outf_tbl_besthit_sim_fasta_like + ".sorted"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by linzhi2013** [comment]
Please search for possible answers from similar questions raised by other users first.

**Comment by liyu123321** [comment]
您好，我是使用的conda-pack安装的mitoz3.6，在运行测试集数据的时候没有问题，我自己的数据也跑了一部分也没有问题，出现这个问题的是我的某一项数据，前面有人类似的问题用新的（空的）目录进行重试成功了，我也进行了尝试，依然出现这个问题。

**Comment by linzhi2013** [comment]
Thanks for your message.

As the first line says **All sequences are low abundance (<10X)**. You may need to provide more data or try different kmers, and assemblers for MT-genome assembly.

**Comment by liyu123321** [comment]
好的我再进行修改尝试，感谢您的答复
