### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by fabianomenegidio** [linzhi2013/MitoZ#22]
NCBI database format is outdated. Upgrading
Downloading taxdump.tar.gz from NCBI FTP site...
Done. Parsing...
Traceback (most recent call last):
  File "/home/rubens/.bin/MitoZ.py", line 2113, in <module>
    check_requiring_taxa(args.requiring_taxa)
  File "/home/rubens/.bin/MitoZ.py", line 1975, in check_requiring_taxa
    ncbi = NCBITaxa()
  File "/home/rubens/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 96, in __init__
    self.update_taxonomy_database()
  File "/home/rubens/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 113, in update_taxonomy_database
    update_db(self.dbfile)
  File "/home/rubens/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 740, in update_db
    upload_data(dbfile)
  File "/home/rubens/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 768, in upload_data
    db.execute(cmd)
sqlite3.OperationalError: database is locked

**Comment by linzhi2013** [comment]
Dear Menegidio,

You can update the NCBI taxonomy database manually.

Open a new terminal, enter the `mitozEnv` environment:

`$ source activate mitozEnv`

Then type:
`$ python` 


Next, in the Python REPL, run:

```
from ete3 import NCBITaxa
ncbi = NCBITaxa()
ncbi.update_taxonomy_database()
```

You may refer to http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html for more details.

Cheers
Guanliang

**Comment by linzhi2013** [comment]
If the problem still exists, you can delete the old database:

`$ rm -rf ~/.etetoolkit/`

then re-install the database manually, please refer to the **3.5 Install NCBI taxonomy database for ete3 package** section in  https://github.com/linzhi2013/MitoZ/blob/master/version_2.4-alpha/INSTALL.md
