### ISSUE TITLE
Failed to download taxdump.tar.gz file for etetoolkit

### ISSUE THREAD

**Issue by jiangzy26** [linzhi2013/MitoZ#72]
Hi,
    I am using the MitoZ programe now, it's good to use, so I am now got a problem.

NCBI database not present yet (first time used?)
Downloading taxdump.tar.gz from NCBI FTP site (via HTTP)...
Traceback (most recent call last):
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MitoZ.py", line 2008, in <module>
    check_requiring_taxa(args.requiring_taxa)
  File "MitoZ.py", line 1975, in check_requiring_taxa
    ncbi = NCBITaxa()
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 110, in __init__
    self.update_taxonomy_database(taxdump_file)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 129, in update_taxonomy_database
    update_db(self.dbfile)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 740, in update_db
    urlretrieve("http://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz", "taxdump.tar.gz")
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/software/biosoft/software/MitoZ/python3/envs/mitozEnv/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

So, what should I do if the server cannot connect to the NCBI

**Comment by linzhi2013** [comment]
Hi Jiang

Yes, thanks for raising the issue. This is true for many Chinese users, who have difficulties in connecting to NCBI.

I have created a etetoolkit database a few days ago and now I am uploading it to Baidu cloud (still uploading due to my bad network),

链接:https://pan.baidu.com/s/1Sa8icV5TVNhfKR4PHWmgow  密码:asuk

# Step 1
 
Download the file 'database.etetoolkit.tar.bz2' into your linux machine, place it into your home directory, i.e. '~/database.etetoolkit.tar.bz2'.
 
 
# Step 2
 
Decompress the file with command:
 
    $ cd ~
    $ tar -xjf database.etetoolkit.tar.bz2
 
then you will get a '.etetoolkit' directory in your home directory, i.e. '~/.etetoolkit'.

Now you can start to use MitoZ, it won't try to download the database again.


You can also use the Docker version, which includes everything to run MitoZ.

**Comment by jiangzy26** [comment]
Hi,
I tried the solution, but I got the new problem

NCBI database format is outdated. Upgrading
Downloading taxdump.tar.gz from NCBI FTP site (via HTTP)...

So, seems the databse is outdated, where we can download the database, and how to make the database.

**Comment by jiangzy26** [comment]
Yes, methods 2 works for me, Thank you very much

**Comment by linzhi2013** [comment]
Great.

**Comment by roguephysicist** [comment]
Hi, I am also having this issue. I am not in China. Am I supposed to download the `database.etetoolkit.tar.bz2` file from the Chinese website? It wants me to install their download software which I have no intention of doing.

Is there any way to convert `taxdump.tar.gz` to the appropriate format, or indeed generate the necessary files that go in `~/.etetoolkit`?

Thanks

**Comment by mlcossette9224** [comment]
@roguephysicist Did you end up finding a solution for this?

**Comment by linzhi2013** [comment]
Hi mlcossette9224,

Did you install the `mitozenv` by yourself? 

You can:
First option:

**download the 'taxdump.tar.gz' file from the Baidu cloud, then open your python terminal (which should be the Python in the mitozEnv environment) and**

链接:https://pan.baidu.com/s/1Sa8icV5TVNhfKR4PHWmgow 密码:asuk

![image](https://user-images.githubusercontent.com/6203542/133388275-baec1f3a-afc2-47a5-b633-b45b49050b05.png)


```
>from ete3 import NCBITaxa
>ncbi = NCBITaxa()
>ncbi.update_taxonomy_database('/path/to/taxdump.tar.gz')
```

NOTE: old versions of **ete3** will **not** work by specifying the `/path/to/taxdump.tar.gz`, you may need to update the `ete3` package firstly before running the above code:

1. Update the `ete3` package when you're in the `mitozenv` environment with command like `conda update  -c etetoolkit ete3`
2. Or you can remove the version specification for the ete3 package when you create the `mitozenv` environment.

**Comment by roguephysicist** [comment]
@mlcossette9224 No, you basically have no alternative than downloading from there. I had a Chinese student that already had an account and was gracious enough to download the file for me. If you want I can share the file with you, but we'd have to do it outside of Github.

**Comment by mlcossette9224** [comment]
@roguephysicist Yes please! My email is mcossette@trentu.ca
