### ISSUE TITLE
can not find taxid for ['Chordata'], maybe it's a misspelling.

### ISSUE THREAD

**Issue by ypchan** [linzhi2013/MitoZ#81]
I run MitoZ.py to assembly a fish mitogenome but the following error occurred.  How to solve the problem, Thanks.
`Base required: 5,000,000,000
Base got: 5,000,000,184
can not find taxid for Chordata
can not find taxid for ['Chordata'], maybe it's a misspelling.
 Please use other taxanomy name.
`
 And I discovered that
 `ncbi = NCBITaxa(taxdump_file='taxdump.tar.gz')
Loading node names...
2273951 names loaded.
228005 synonyms loaded.
Loading nodes...
2273951 nodes loaded.
Linking nodes...
Tree is loaded.
Updating database: /data/6190113/.etetoolkit/taxa.sqlite ...
 2273000 generating entries...
Uploading to /data/6190113/.etetoolkit/taxa.sqlite

Inserting synonyms:      115000 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/6190113/soft/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/                             ete3/ncbi_taxonomy/ncbiquery.py", line 106, in __init__
    self.update_taxonomy_database(taxdump_file)
  File "/data/6190113/soft/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/                             ete3/ncbi_taxonomy/ncbiquery.py", line 131, in update_taxonomy_database
    update_db(self.dbfile, taxdump_file)
  File "/data/6190113/soft/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/                             ete3/ncbi_taxonomy/ncbiquery.py", line 760, in update_db
    upload_data(dbfile)
  File "/data/6190113/soft/miniconda3/envs/mitozEnv/lib/python3.6/site-packages/                             ete3/ncbi_taxonomy/ncbiquery.py", line 802, in upload_data
    db.execute("INSERT INTO synonym (taxid, spname) VALUES (?, ?);", (taxid, spn                             ame))
sqlite3.IntegrityError: UNIQUE constraint failed: synonym.spname, synonym.taxid
`

**Comment by linzhi2013** [comment]
Hi Chen,

same problem as here (https://github.com/linzhi2013/MitoZ/issues/79#issuecomment-689908569), which has been addressed.

**Comment by linzhi2013** [comment]
Going to close this and please feel free to raise new issues.
